server:
  port: 80

#开启Hystrix的服务降级功能
feign:
  hystrix:
    enabled: true
      
      

#集群配置
#配置ribbon整合信息
eureka:
  client:
    register-with-eureka: false #禁止将自己注册到服务中心中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/